

import java.awt.*;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.net.InetAddress;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author David
 */
public class Login extends javax.swing.JFrame {
    Connection conn = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    public static Boolean UserAdmin = false;
    public static String User_ID;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Password_Field = new javax.swing.JPasswordField();
        Username_Field = new javax.swing.JFormattedTextField();
        Login_button = new javax.swing.JButton();
        Cancel_Button_Panel = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        Admin_CheckBox = new javax.swing.JCheckBox();
        Login_Message_Label = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(440, 300));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(241, 241, 241));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Password_Field.setBackground(new java.awt.Color(241, 241, 241));
        Password_Field.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        Password_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Password", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Light", 0, 15))); // NOI18N
        jPanel1.add(Password_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 140, 380, 70));

        Username_Field.setBackground(new java.awt.Color(241, 241, 241));
        Username_Field.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Username", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Yu Gothic UI Light", 0, 15))); // NOI18N
        Username_Field.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 25)); // NOI18N
        jPanel1.add(Username_Field, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, 380, 70));

        Login_button.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Login_button.setText("Login");
        Login_button.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Login_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Login_buttonMouseClicked(evt);
            }
        });
        jPanel1.add(Login_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 260, 90, -1));

        Cancel_Button_Panel.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 20)); // NOI18N
        Cancel_Button_Panel.setText("Cancel");
        Cancel_Button_Panel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Cancel_Button_Panel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cancel_Button_PanelActionPerformed(evt);
            }
        });
        jPanel1.add(Cancel_Button_Panel, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, -1, -1));

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        jLabel1.setText("DavidFix's Car Maintenance App");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, -1, -1));

        Admin_CheckBox.setFont(new java.awt.Font("Yu Gothic UI Light", 0, 15)); // NOI18N
        Admin_CheckBox.setText("Administrator");
        Admin_CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Admin_CheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(Admin_CheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));
        jPanel1.add(Login_Message_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 40, 180, 30));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 310));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
      public void AdminLogin(){
        conn = mysql.ConnectDB();
        String Sql = "SELECT * FROM Administrator where Username = ? and Password = ?";
                try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1,Username_Field.getText());
            pst.setString(2, Password_Field.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                User_ID = rs.getString(1);
                this.hide();
                loading splash = new loading();
                splash.setVisible(true); 
                
                try {
                    for(int i = 0; i <= 100; i++) {
                        if(i == 1){
                            main w = new main();
                            splash.setVisible(false);
                            w.setVisible(true);
                        }
                    }
                } catch (Exception e) {
                    
                }
                String Student_Name = rs.getString(2) + " " + rs.getString(3);

                conn = mysql.ConnectDB();
                    try{
                        conn.close();
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }

                rs.close();
            }
            else{
                //JOptionPane.showMessageDialog(null, "Invalid Username or Password", "Access Denied", JOptionPane.ERROR_MESSAGE);
                Login_Message_Label.setText("Invalid User or Password!");
            } 
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    public void UserLogin(){
        conn = mysql.ConnectDB();
        String Sql = "SELECT * FROM User where Username = ? and Password = ?"; //SELECT TOP 1
                try{
            pst = conn.prepareStatement(Sql);
            pst.setString(1,Username_Field.getText());
            pst.setString(2, Password_Field.getText());
            rs = pst.executeQuery();
            if(rs.next()){
                User_ID = rs.getString(1);
                this.hide();
                loading splash = new loading();
                splash.setVisible(true);
                try {
                    for(int i = 0; i <= 3000; i++) {
                        if(i == 1){
                            main w = new main();
                            splash.setVisible(false);
                           w.setVisible(true);
                        }
                    }
                } catch (Exception e) {
                    
                }
                String Student_Name = rs.getString(2) + " " + rs.getString(3);

                conn = mysql.ConnectDB();
                    try{
                        conn.close();
                    }catch (Exception e) {
                        JOptionPane.showMessageDialog(rootPane, e);
                    }

                rs.close();
            }
            else{
                //JOptionPane.showMessageDialog(null, "Invalid Username or Password", "Access Denied", JOptionPane.ERROR_MESSAGE);
                Login_Message_Label.setText("Invalid User or Password!");
            } 
        } catch(HeadlessException | SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
        
 
    private void Cancel_Button_PanelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cancel_Button_PanelActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Cancel_Button_PanelActionPerformed

    private void Login_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Login_buttonMouseClicked
        // TODO add your handling code here:
                if (Login.UserAdmin == true){
            AdminLogin();
        }
        else if ((Login.UserAdmin == false))
        {
            UserLogin();
        }
    }//GEN-LAST:event_Login_buttonMouseClicked

    private void Admin_CheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Admin_CheckBoxActionPerformed
        // TODO add your handling code here:
                        if(Admin_CheckBox.isSelected()){
            Login.UserAdmin = true;        }
        else
        {
            Login.UserAdmin = false;
        }
    }//GEN-LAST:event_Admin_CheckBoxActionPerformed
                                                    

                                      
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

 
 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Admin_CheckBox;
    private javax.swing.JButton Cancel_Button_Panel;
    private javax.swing.JLabel Login_Message_Label;
    private javax.swing.JButton Login_button;
    private javax.swing.JPasswordField Password_Field;
    private javax.swing.JFormattedTextField Username_Field;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
